# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [15]:
import numpy as np
arr = np.random.randint(1, 21, size=(5, 5))
arr[:, 2] = 1
print(arr )

print()

arr2 = np.arange(1, 17).reshape((4, 4))
np.fill_diagonal(arr2, 0)
print(arr2)

[[13 19  1  6 11]
 [20  7  1 16  1]
 [13 16  1  2 11]
 [15  1  1  4  2]
 [11  2  1 10  6]]

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [25]:
six_by_six = np.arange(1, 37).reshape((6, 6))
extracted_arr = six_by_six[2:6, 1:4]
print(extracted_arr)

print()

new_array = np.random.randint(1, 100, size=(5, 5))
print(new_array)

border_elements = np.concatenate((new_array[0, :], new_array[-1, :], new_array[1:-1, 0], new_array[1:-1, -1]))
print(border_elements)

[[14 15 16]
 [20 21 22]
 [26 27 28]
 [32 33 34]]

[[70 23 71 97 69]
 [20 30  5 52 91]
 [33 89 40 58 72]
 [34 65 75 70 88]
 [14 99 35 43  8]]
[70 23 71 97 69 14 99 35 43  8 20 33 34 91 72 88]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [31]:
arr1 = np.random.randint(1, 10, size=(3, 4))
arr2 = np.random.randint(1, 10, size=(3, 4))

print("Array 1: \n")
print(arr1)

print("\nArray 2: \n")
print(arr2)

print("\nSum")
sum = arr1 + arr2
print(sum)
print()

print("\nDifference")
diff = arr1 - arr2
print(diff)
print()

print("\nProduct")
prod = arr1 * arr2
print(prod)
print()

print("\nDivision")
div = arr1 / arr2
print(div)

Array 1: 

[[7 2 1 8]
 [1 7 6 8]
 [1 6 9 6]]

Array 2: 

[[4 1 5 2]
 [8 8 4 5]
 [9 3 1 3]]

Sum
[[11  3  6 10]
 [ 9 15 10 13]
 [10  9 10  9]]


Difference
[[ 3  1 -4  6]
 [-7 -1  2  3]
 [-8  3  8  3]]


Product
[[28  2  5 16]
 [ 8 56 24 40]
 [ 9 18  9 18]]


Division
[[1.75       2.         0.2        4.        ]
 [0.125      0.875      1.5        1.6       ]
 [0.11111111 2.         9.         2.        ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [38]:
arr = np.arange(1, 17).reshape((4, 4))
print(arr)

print("\nRow wise sum")
print(arr.sum(axis = 1))

print("\nColumn wise sum")
print(arr.sum(axis = 0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row wise sum
[10 26 42 58]

Column wise sum
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [41]:
arr = np.random.randint(1, 10, size=(5, 5))
print(arr)

print("\nMean")
print(np.mean(arr))

print("\nMedian")
print(np.median(arr))

print("\nStandard Deviation")
print(np.std(arr))

print("\nVariance")
print(np.var(arr))

[[7 5 9 9 9]
 [6 4 5 7 3]
 [1 2 5 1 7]
 [1 2 2 8 9]
 [6 2 5 2 9]]

Mean
5.04

Median
5.0

Standard Deviation
2.835207223467096

Variance
8.0384


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [42]:
arr = np.arange(1, 10).reshape((3, 3))

mean = np.mean(arr)
st_dev = np.std(arr)

normalized_array = (arr - mean) / st_dev

print(normalized_array)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [45]:
arr = np.random.randint(1, 11, size=(3, 3))
print(arr)

add = np.random.randint(1, 11, size=(3,))
print(add)

print(arr + add)

[[1 1 7]
 [3 3 2]
 [1 2 1]]
[10  3  7]
[[11  4 14]
 [13  6  9]
 [11  5  8]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [47]:
arr = np.random.randint(1, 11, size=(4, 4))
sub = np.random.randint(1, 11, size=(4, ))

print("Array\n")
print(arr)

print("\nSub array\n")
print(sub)

print("\nResult\n")
print(arr - sub)

Array

[[ 6  3  1  3]
 [ 7  4  9  7]
 [ 6  6  6  7]
 [10  1  2  5]]

Sub array

[9 5 4 6]

Result

[[-3 -2 -3 -3]
 [-2 -1  5  1]
 [-3  1  2  1]
 [ 1 -4 -2 -1]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [60]:
matrix = np.random.randint(1, 11, size=(3, 3))
print(matrix)

print("\nDeterminant")
determinant = np.linalg.det(matrix)
print(determinant)

print("\nInverse")
invert = np.linalg.inv(matrix)
print(invert)

print("\nEigenvalues")
eigenvalues = np.linalg.eigvals(matrix)
print(eigenvalues)

[[10  9  4]
 [ 9  7  7]
 [ 7  8  6]]

Determinant
-92.99999999999994

Inverse
[[ 0.15053763  0.23655914 -0.37634409]
 [ 0.05376344 -0.34408602  0.3655914 ]
 [-0.24731183  0.1827957   0.11827957]]

Eigenvalues
[22.50534636  2.29513589 -1.80048225]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [61]:
arr1 = np.arange(1, 7).reshape((2, 3))
arr2 = np.random.randint(1, 6, size=(3, 2))

print("\nArray 1")
print(arr1)

print("\nArray 2")
print(arr2)

mult = np.linalg.matmul(arr1, arr2)
print("\nMultiplication")
print(mult)


Array 1
[[1 2 3]
 [4 5 6]]

Array 2
[[4 4]
 [4 2]
 [4 3]]

Multiplication
[[24 17]
 [60 44]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [63]:
arr = np.arange(1, 10).reshape((3, 3))
print("\nOriginal array")
print(arr)

print("\n1 x 9 array")
print(arr.reshape((1, 9)))

print("\n9 x 1 array")
print(arr.reshape((9, 1)))


Original array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1 x 9 array
[[1 2 3 4 5 6 7 8 9]]

9 x 1 array
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [68]:
arr = np.random.randint(1, 10, size=(5, 5))
print("\nOriginal array")
print(arr)

flat_array = arr.flatten()
print("\nFlat array: ")
print(flat_array)

back_to_five = flat_array.reshape((5, 5))
print("\nBack to 5")
print(back_to_five)


Original array
[[9 8 1 4 6]
 [2 4 4 4 3]
 [2 5 3 2 7]
 [7 2 9 4 2]
 [7 8 3 6 8]]

Flat array: 
[9 8 1 4 6 2 4 4 4 3 2 5 3 2 7 7 2 9 4 2 7 8 3 6 8]

Back to 5
[[9 8 1 4 6]
 [2 4 4 4 3]
 [2 5 3 2 7]
 [7 2 9 4 2]
 [7 8 3 6 8]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [72]:
arr = np.random.randint(1, 11, size=(5, 5))
print("\nOriginal array")
print(arr)


print("\nCorner elements")
print(arr[[0, 0, -1, -1], [0, -1, 0, -1]])



Original array
[[ 1  5  4  7  4]
 [10  8  5  8  9]
 [ 5  4  1  8  9]
 [ 3  2  9  8 10]
 [ 8 10  4  4  8]]

Corner elements
[1 4 8 8]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [74]:
arr = np.random.randint(1, 15, size=(4, 4))
print(arr)
arr[arr > 10] = 10

print(arr)

[[12  6  5  2]
 [ 4 11 11  9]
 [ 1  6 10  8]
 [ 3  7  1  2]]
[[10  6  5  2]
 [ 4 10 10  9]
 [ 1  6 10  8]
 [ 3  7  1  2]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [77]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

data = np.array([('John', 10, 50.0), ('Ram', 11, 55.0), ('Shyam', 9, 45.0)], dtype=data_type)
print(data)

np.sort(data, order='age')


[('John', 10, 50.) ('Ram', 11, 55.) ('Shyam',  9, 45.)]


array([('Shyam',  9, 45.), ('John', 10, 50.), ('Ram', 11, 55.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [82]:
data_type = [('x', 'i4'), ('y', 'i4')]

data = np.array([(1, 1), (2, 2), (3, 3)], dtype=data_type)
print(data)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print(distances)

[(1, 1) (2, 2) (3, 3)]
[[0.         1.41421356 2.82842712]
 [1.41421356 0.         1.41421356]
 [2.82842712 1.41421356 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.


In [84]:
import numpy.ma as ma

arr = np.random.randint(1, 20, size=(4, 4))
print("\nOriginal array")
print(arr)

print("\nMaskdedArray")
masked_array = ma.masked_greater(arr, 10)
print(masked_array)

print("\nSum of masked array")
print(np.sum(masked_array))



Original array
[[14  1  1  8]
 [ 3 14 14 11]
 [10  7 19  4]
 [ 6  9 17 12]]

MaskdedArray
[[-- 1 1 8]
 [3 -- -- --]
 [10 7 -- 4]
 [6 9 -- --]]

Sum of masked array
49


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [91]:
# Create a masked array of shape (3, 3) with random integers
import numpy.ma as ma
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[16 13  7]
 [ 3 12  1]
 [ 4 20 12]]
Masked array:
[[-- 13 7]
 [3 -- 1]
 [4 20 --]]
Modified masked array:
[[ 8 13  7]
 [ 3  8  1]
 [ 4 20  8]]
